import './global.css';
import '@bryntum/core-thin/core.classic-dark.css';
import '@bryntum/grid-thin/grid.classic-dark.css';

export const metadata = {
  title: 'Welcome to leap',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
